import Head from "next/head";
import Image from "next/image";
import Header from "../../components/header";

export default function Movies() {
  return (
    <div>
      <Head>
        <title>Movies</title>
        <meta
          name="description"
          content="Generated by PT. Bank Raya Indonesia, Tbk"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <div style={{ marginTop: "200px", textAlign: "center" }}>
        Movie Detail
      </div>
    </div>
  );
}
