import Head from "next/head";
import { useEffect, useState } from "react";
import Header from "../../components/header";
import CardMovies from "../../components/card";
import axios from "axios";
import { InputGroup, Button, Input } from "reactstrap";

export default function Movies({ moviesInitial }) {
  const [movieName, setMovieName] = useState("");
  const [movies, setMovies] = useState(moviesInitial);

  function searchMovies() {
    return axios({
      method: "get",
      url: `${process.env.NEXT_PUBLIC_API_SEARCH_URL}`,
      params: {
        query: movieName,
      },
    })
      .then((res) => {
        console.log(res);
        setMovies(res.data.results);
      })
      .catch((error) => {
        console.log(error);
        alert("Data yang anda cari tidak ditemukan");
      });
  }

  return (
    <div>
      <Head>
        <title>Movies</title>
        <meta
          name="description"
          content="Generated by PT. Bank Raya Indonesia, Tbk"
        />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
          crossOrigin="anonymous"
        />
      </Head>
      <Header />
      <div>
        <h4 style={{ padding: "8rem 4rem 0rem 4rem" }}>Popular Movies</h4>
      </div>
      <div className="main-container">
        <div className="search-container">
          <InputGroup>
            <Input onChange={(e) => setMovieName(e.target.value)} />
            <Button onClick={() => searchMovies()}>Cari</Button>
          </InputGroup>
        </div>
        <CardMovies movies={movies} />
      </div>
    </div>
  );
}

export async function getServerSideProps() {
  const moviesData = await fetch(`${process.env.NEXT_PUBLIC_API_BASE_URL}`, {
    method: "get",
  });

  const moviesDataInitial = await moviesData.json();
  const moviesInitial = moviesDataInitial.results
    ? moviesDataInitial.results
    : [];

  return {
    props: { moviesInitial },
  };
}
