import Head from "next/head";
import Image from "next/image";
import Header from "../components/header";
import CardMovies from "../components/card";

export default function Home({ movies }) {

  return (
    <div>
      <Head>
        <title>Home</title>
        <meta
          name="description"
          content="Generated By PT. Bank Raya Indonesia, Tbk"
        />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
          crossOrigin="anonymous"
        />
      </Head>
      <Header />
      <div>
        <h4 className="title-page">Popular Movies</h4>
      </div>
      <div className="main-container">
        <CardMovies movies={movies} />
      </div>
    </div>
  );
}

export async function getServerSideProps() {
  const moviesData = await fetch(`${process.env.NEXT_PUBLIC_API_BASE_URL}`, {
    method: "get",
  });

  const moviesDataInitial = await moviesData.json();
  const movies = moviesDataInitial.results ? moviesDataInitial.results : [];

  return {
    props: { movies },
  };
}
