import Head from "next/head";
import React, { useState } from "react";
import Header from "../../../components/header";
import {
  Accordion,
  AccordionBody,
  AccordionHeader,
  AccordionItem,
  Col,
  Row,
} from "reactstrap";

export default function DetailMovie({ id, movieInitial }) {

  const [genres, setGenres] = useState(movieInitial.genres);
  const [open, setOpen] = useState("1");
  const toggle = (id) => {
    if (open === id) {
      setOpen();
    } else {
      setOpen(id);
    }
  };
  return (
    <div>
      <Head>
        <title>Detail Movie</title>
        <meta
          name="description"
          content="Generated by PT. Bank Raya Indonesia, Tbk"
        />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
          crossOrigin="anonymous"
        />
      </Head>
      <Header />
      <div className="main-container">
        <div className="image-detail-container">
          <Row>
            <Col className="col-lg-6 col-sm-12 col-md-6 mb-4" xs="12">
              <img
                alt=""
                className="image-detail"
                src={`${process.env.NEXT_PUBLIC_IMAGE_MOVIES_BASE_URL}${movieInitial.poster_path}`}
              />
            </Col>
            <Col className="col-lg-6 col-sm-12 col-md-6 mb-4" xs="12">
              <div className="movie-detail-text">
                <div className="movie-detail-text-title">
                  <h3>{movieInitial.original_title}</h3>
                </div>
                <Row>
                  <Col className="col-lg-4 col-sm-4 col-md-4 mb-4">
                    <div className="detail-text">Bahasa</div>
                    <div className="detail-text">Kategori Dewasa</div>
                    <div className="detail-text">Genre</div>
                    <div className="detail-text">Popularity</div>
                    <div className="detail-text">Produksi</div>
                    <div className="detail-text">Negara</div>
                    <div className="detail-text">Tanggal Rilis</div>
                    <div className="detail-text">Tagline</div>
                    <div className="detail-text">Ratings</div>
                    <div className="detail-text">Overview</div>
                  </Col>
                  <Col className="col-lg-8 col-sm-8 col-md-8 mb-4">
                    <div className="detail-text"> : {movieInitial.original_language}</div>
                    <div className="detail-text"> : {movieInitial.adult ? "Ya" : "Tidak"}</div>
                    <div className="detail-text"> : {genres.map((item) => {
                        return `${item.name} `;
                      })}
                    </div>
                    <div className="detail-text"> : {movieInitial.popularity}</div>
                    <div className="detail-text"> : {movieInitial.production_companies[0].name}</div>
                    <div className="detail-text"> : {movieInitial.production_countries[0].name}</div>
                    <div className="detail-text"> : {movieInitial.release_date}</div>
                    <div className="detail-text"> : {movieInitial.tagline}</div>
                    <div className="detail-text"> : {movieInitial.vote_average}</div>
                    <div className="detail-text"> : {movieInitial.overview}</div>
                  </Col>
                </Row>
              </div>
            </Col>
          </Row>
        </div>
      </div>
    </div>
  );
}

export async function getServerSideProps(context) {
  const id = context.query.id;
  const movieData = await fetch(
    `${process.env.NEXT_PUBLIC_MOVIE_DETAIL}${id}${process.env.NEXT_PUBLIC_API_KEY}`,
    {
      method: "get",
    }
  );

  const movieDataInitial = await movieData.json();
  const movieInitial = movieDataInitial ? movieDataInitial : [];

  return {
    props: {
      id,
      movieInitial,
    },
  };
}
